steps:
  - group: ":gandalf: Test Group"
    key: "test-group"
    steps:
      - command: "echo 'Running tests'"
        agent_query_rules:
         - queue=default
        label: "Run tests"

  - group: ":gandalf: Deploy Group"
    key: "deploy-group"
    steps:
      - command: "echo 'Deploying app'"
        agent_query_rules:
         - queue=default
        label: "Deploy app"
