steps:
  - label: "Do thing"
    command: echo "Build completed!"
notify:
  - slack:
      channels:
        - "#test-customers-issue"
      message: "This is the Build URL: ${BUILDKITE_BUILD_URL}\n and the build was created by: ${BUILDKITE_BUILD_CREATOR_EMAIL} "
