steps:
  - label: "🤡 :hammer:"
    plugins:
      - docker-compose#v3.5.0:
          run: tests
  - label: ":sparkles: lint"
    plugins:
      - plugin-linter#v2.0.0:
          id: detect-clowns
  - label: ":shell: Shellcheck"
    plugins:
      - shellcheck#v1.1.2:
          files: hooks/**
