steps:
  - label: "Example Step"
    command: echo "This step is correct"
  - label: "This step will cause an error"
    command: echo "This step has a syntax error"
  - label: "Another Step"
    command:
