steps:
  - label: "🤡 :hammer:"
    agents:
      linux: "true"
    plugins:
      - plugin-tester#v1.1.0: ~

  - label: ":sparkles: lint"
    agents:
      linux: "true"
    plugins:
      - plugin-linter#v3.2.0:
          id: detect-clowns

  - label: ":shell: Shellcheck"
    agents:
      linux: "true"
    plugins:
      - shellcheck#v1.3.0:
          files: hooks/**
