steps:
  - label: "🤡 :hammer:"
    plugins:
      - docker-compose#v2.6.0:
          run: tests
  - label: ":sparkles: lint"
    plugins:
      - plugin-linter#v2.0.0:
          id: detect-clowns
  - label: ":shell: Shellcheck"
    plugins:
      - shellcheck#v1.1.1:
          files: hooks/**
