steps:
  - label: "Example Step"
    command: echo $(BUILDKITE_AGENT_ID)
  - label: "This step will cause an error"
    command: echo "This step has a syntax error"
  - label: "Another Step"
    command: echo "$BUILDKITE_MESSAGE"
