env: &env
  TIME_ZONE: "America/Los_Angeles"
  BUILDKITE_AGENT_LOG_LEVEL: "error"
  BUILDKITE_CLEAN_CHECKOUT: "true"
  LANG: en_US.UTF-8
  LC_ALL: en_US.UTF-8
  AWS_DEFAULT_REGION: us-east-1
  AWS_REGION: us-east-1

retry_command: &retry_command
  automatic:
    - exit_status: -1  # agent was lost
      limit: 2
    - exit_status: 99  # AWS credentials
      limit: 5
    - exit_status: 125 # unexpected EOF
      limit: 2
    - exit_status: 255 # agent was shutdown
      limit: 2

plugin_config: &plugin_config
  plugins:
    - ssh://git@github.com/TinderBackend/scaffold-buildkite.git#v0.2.18:
        environment:
          variables:
            # This is a protected env var, so need to be set via plugin procedure.
            - name: BUILDKITE_GIT_CLEAN_FLAGS
              value: "-n"
        secret:
          entries:
            - group: "client"
              kind: "account"
              entity: "ios-devxp-bk-github"
              key: "pat"
              environ_variable: "GITHUB_API_TOKEN"
            - group: "client"
              kind: "account"
              entity: "ios-artifactory-librelease-access"
              key: "password"
              environ_variable: "ARTIFACTORY_PASSWORD"
            - group: "client"
              kind: "account"
              entity: "ios-artifactory-librelease-access"
              key: "username"
              environ_variable: "ARTIFACTORY_USER"
            - group: "client"
              kind: "account"
              entity: "ios-bep-file"
              key: "password"
              environ_variable: "BEP_FILE_PASSWORD"
            - group: "client"
              kind: "application"
              entity: "slack-webhook"
              key: "url"
              environ_variable: "SLACK_WEBHOOK_URL"
            - group: "client"
              kind: "account"
              entity: "ios-sonarqube"
              key: "token"
              environ_variable: "BUILDKITE_SONARQUBE_TOKEN"
            - group: "client"
              kind: "account"
              entity: "buildkite-readonly"
              key: "token"
              environ_variable: "BUILDKITE_READONLY_ACCESS_TOKEN"
            - group: "client"
              kind: "account"
              entity: "ios-emergetool"
              key: "token"
              environ_variable: "IOS_EMERGETOOL_TOKEN"
            - group: "client"
              kind: "account"
              entity: "ios-appleconnect"
              key: "issuer-id"
              environ_variable: "ISSUER_ID"
            - group: "client"
              kind: "account"
              entity: "ios-appleconnect"
              key: "key"
              environ_variable: "KEY_IDENTIFIER"
            - group: "client"
              kind: "account"
              entity: "ios-devxp-jira"
              key: "user-email"
              environ_variable: "JIRA_USER_EMAIL"
            - group: "client"
              kind: "account"
              entity: "ios-devxp-jira"
              key: "token"
              environ_variable: "JIRA_API_TOKEN"
            - group: "client"
              kind: "account"
              entity: "ios-devxp-bk-test-analytics"
              key: "token"
              environ_variable: "BUILDKITE_TEST_ANALYTICS_TOKEN_TINDER_IOS"
            - group: "client"
              kind: "account"
              entity: "ios-ec2-user"
              key: "password"
              environ_variable: "NODE_PASSWD"
            - group: "client"
              kind: "account"
              entity: "ios-devxp-screenshotbot-api"
              key: "token"
              environ_variable: "SCREENSHOTBOT_API_KEY_TINDER_IOS"
            - group: "client"
              kind: "account"
              entity: "ios-devxp-screenshotbot-api"
              key: "secret"
              environ_variable: "SCREENSHOTBOT_API_SECRET_TINDER_IOS"
            - group: "backend"
              kind: "account"
              entity: "scaffold-github"
              key: "api-token"
              environ_variable: "BUILDKITE_ACCESS_TOKEN"
            - group: "client"
              kind: "account"
              entity: "apple-application"
              key: "password"
              environ_variable: "APPLE_APPLICATION_SPECIFIC_PASSWORD"
            - group: "client"
              kind: "account"
              entity: "ios-fastlane"
              key: "password"
              environ_variable: "FASTLANE_PASSWORD"
            - group: "client"
              kind: "account"
              entity: "ios-fastlane"
              key: "session"
              environ_variable: "FASTLANE_SESSION"
            - group: "client"
              kind: "application"
              entity: "1713201421-ios-distribution"
              key: "key"
              file_path: "/tmp/client-secrets/client.application.1713201421-ios-distribution.key"
              file_permission: "600"
            - group: "client"
              kind: "application"
              entity: "verify-archive-google-application"
              key: "credential"
              file_path: "/tmp/client-secrets/client.application.verify-archive-google-application.credential"
              file_permission: "600"
            - group: "client"
              kind: "account"
              entity: "tinder-enterprise"
              key: "certificate"
              file_path: "/tmp/client-secrets/client.account.tinder-enterprise.certificate"
              file_permission: "600"
            - group: "client"
              kind: "account"
              entity: "tinder-enterprise"
              key: "token"
              file_path: "/tmp/client-secrets/Tinder_Enterprise_private_key.p12"
              file_permission: "600"
            - group: "client"
              kind: "account"
              entity: "apple-connect"
              key: "api-key"
              file_path: "/tmp/client-secrets/client.account.apple-connect.api-key"
              file_permission: "600"


<<: *env

steps:
  - command: ".buildkite/scripts/target_selection.sh"
    name: "Target Selection"
    key: "target_selection"
    timeout_in_minutes: 20 # 20 minutes
    retry:
      <<: *retry_command
    <<: *plugin_config

  - command: ".buildkite/scripts/bazel.sh"
    name: "Bazel Smart Tests"
    key: "smart_tests"
    depends_on: "target_selection"
    timeout_in_minutes: 120 # 2 hours
    retry:
      <<: *retry_command
    <<: *plugin_config

  - command: ".buildkite/scripts/verify_local_developer_workflows.sh"
    name: "Verify Local Developer Workflows"
    key: "verify_local_developer_workflows"
    depends_on: "target_selection"
    timeout_in_minutes: 30
    retry:
      <<: *retry_command
    <<: *plugin_config

  - command: ".buildkite/scripts/static_analysis.sh"
    name: "Static Analysis"
    key: "static_analysis"
    branches: "main"
    timeout_in_minutes: 20 # 20 minutes
    retry:
      <<: *retry_command
    <<: *plugin_config

  - command: ".buildkite/scripts/verify_archive.sh"
    name: "Verify Archive"
    key: "verify_archive"
    timeout_in_minutes: 40 # 40 minutes
    retry:
      automatic:
        limit: 1
    <<: *plugin_config

  - command: ".buildkite/scripts/deploy_apps.sh"
    name: "Deploy Apps"
    key: "deploy_apps"
    timeout_in_minutes: 40 # 40 minutes
    env:
      DEPLOY_APPS_TARGET_NAME: "//Projects/Tinder/Tinder:Tinder_BuildForDevice"
      DEPLOY_APPS_FIREBASE_APP_ID: "1:465293127427:ios:8d5c05c43b988158"
      DEPLOY_APPS_FIREBASE_GROUP: "iOS_PR_Tinder_AdhocDevtools_distribution"
      DEPLOY_APPS_BUGSNAG_API_KEY: "add6d95c8c0796dd5f7cac9b7349fae6"
      DEPLOY_APPS_RELEASE_NOTES: "[PR]"
    retry:
      <<: *retry_command
    soft_fail:
      - exit_status: 1
    <<: *plugin_config

  - command: ".buildkite/scripts/app_launch_verification.sh"
    name: "App Launch Verification"
    key: "app_launch_verification"
    timeout_in_minutes: 40 # 40 minutes
    retry:
      <<: *retry_command
    <<: *plugin_config

  - trigger: "tinder-ios-ui-tests"
    label: "Trigger UI Tests"
    depends_on: "target_selection"
    # [CW] 6/28/24 - Currently, primary CI success should not be coupled to UI Testing failures.
    soft_fail: true
    async: true
    build:
      # [Kai] 7/9/24 - There is a bug of save dynamic pipeline during a revert commit message. 
      # More details can be found in the Slack thread: https://tinder.slack.com/archives/C01UDTX551T/p1720548024100329?thread_ts=1720471865.533509&cid=C01UDTX551T
      # Let's use a fixed message instead of save dynamic pipeline until Buildkite fixes the bug.
      branch: devxp/kai/use_fixed_message_until_bk_fix_bug
      commit: b126e3799091f6fcffb88d01b4ac6f040818d630
      message: "Trigger UI Tests"
      env:
        BUILDKITE_PULL_REQUEST: 53768
        BUILDKITE_PULL_REQUEST_BASE_BRANCH: main
        BUILDKITE_PULL_REQUEST_REPO: https://github.com/TinderApp/tinder_ios.git
        BUILD_QUEUE: ios-mac2.metal-macos14.3-xcode15.3-apb1
