steps:
  - label: "Example Step"
    command: echo "This step is correct"
  - label: "This step will cause an error"
    env:
      BUILDKITE_MESSAGE: Revert "Fix X button not dismissing `WebViewController` (#53506)" This reverts commit 1b1bc47826aed5bc4cddc023aacd18b8614c442a.
    command: echo "BUILDKITE_MESSAGE is: $BUILDKITE_MESSAGE"

  
