steps:
  - label: "Parse BUILDKITE_MESSAGE"
    env:
      BUILDKITE_MESSAGE: "Revert \"Fix X button not dismissing `WebViewController` (#53506)\"
    command: echo "BUILDKITE_MESSAGE is: $BUILDKITE_MESSAGE"
