steps:
  - label: "Step1"
    command: echo "exit -1"
notify:
  # Notify private channel
  - slack:
      channels:
        - "buildkite#test-customers-issue"
    if: build.state == "failed" || pipeline.started_passing

