steps:
  #   Multiline / trailing-space secret
  - label: " Multiline secret"
    commands: |
      printf 'line1\nline2 ' > secret.txt
      buildkite-agent redactor add secret.txt
      echo -e "line1 line2"

  #   Non-ASCII characters
  - label: " Non-ASCII secret"
    commands: |
      echo 'pässw🔑rd' | buildkite-agent redactor add
      echo 'pässw🔑rd appears here'

  #   Regex-looking characters
  - label: " Regex-y secret"
    commands: |
      echo 'a.*b?c' | buildkite-agent redactor add
      echo 'a.*b?c a.*b?c'

  # 4️  Long (≈2 KiB) secret – full round-trip
  - label: " Long secret (2 KiB)"
    commands: |
    # create one long *single-line* secret (~2 KiB)
    head -c 2048 </dev/urandom | base64 | tr -d '\n' > bigsecret.txt

    # register the whole value
    buildkite-agent redactor add bigsecret.txt

    # echo it back exactly as stored
    cat bigsecret.txt

  #   Overlapping secrets (prefix + full)
  - label: " Overlapping secrets"
    commands: |
      echo 'abc'     | buildkite-agent redactor add
      echo 'abcdef'  | buildkite-agent redactor add
      echo 'abc abcdef'

  #   Same secret repeated on one line
  - label: " Repeated secret same line"
    commands: |
      echo 'spam' | buildkite-agent redactor add
      echo 'spam spam spam'

  #  Persistence across multiple commands
  - label: " Persistence in step"
    commands: |
      echo 'staysecret' | buildkite-agent redactor add
      echo 'staysecret first time'
      echo 'staysecret second time'

  #   Secret leaked from a “hook / plugin”-style script
  - label: " Hook‐style output"
    commands: |
      echo 'hooksecret' | buildkite-agent redactor add
      cat > plugin-script.sh <<'EOF'
      #!/usr/bin/env bash
      echo "Inside plugin hook: hooksecret"
      EOF
      chmod +x plugin-script.sh
      ./plugin-script.sh

  #   File with no trailing newline
  - label: " No-newline file"
    commands: |
      printf 'nonewline' > nn.txt
      buildkite-agent redactor add nn.txt
      echo 'nonewline'

  #   Mixed json / none formats
  - label: " Mixed formats"
    commands: |
      echo '{"jsonkey":"jsonsecret"}' | buildkite-agent redactor add --format json
      echo 'plainsecret' | buildkite-agent redactor add
      echo 'jsonsecret plainsecret'

  #   Binary file content
  - label: " Binary secret"
    commands: |
      cp "$(command -v ls)" /tmp/ls.bin       # any small binary will do
      buildkite-agent redactor add /tmp/ls.bin
      xxd -l 32 /tmp/ls.bin                   # should print [REDACTED]

  #   Parallelism: secret added in every shard
  - label: "Parallel shards"
    parallelism: 3
    commands: |
      echo 'parallelsecret' | buildkite-agent redactor add
      echo "Shard ${BUILDKITE_PARALLEL_JOB}: parallelsecret"
