steps:
  - label: "Echo Wrong Variable with Bash Expansion"
    command:
      - export CORRECT_VAR="This is the correct variable"
      - export WRONG_VAR="$(echo blah)"
    - echo $CORRECT_VAR
      - echo $WRONG_VAR
