steps:
  - label: "Step 1 - Duplicate Key"
    key: duplicate-key
    command: echo "Running Step 1"

  - label: "Step 2 - Duplicate Key"
    key: duplicate-key  # Reusing the same key
    command: echo "Running Step 2"
