steps:
  - group: ":gandalf: Test Group"
    key: "test-group"
    steps:
      - command: "echo 'Creating new role'"
        agent_query_rules:
         - queue=default-queue
        label: "Run tests script"


