steps:
  - group: ":gandalf: Deploy Group"
    key: "deploy-group-test"
    steps:
      - command: "tests/graceful_shutdown_script.sh"
        agent_query_rules:
         - queue=default-queue
        label: "Deploy app"
