steps:
  - label: ":wave: Show Cancel Signal"
    command: |
      echo "BUILDKITE_CANCEL_SIGNAL is: $BUILDKITE_CANCEL_SIGNAL"
  - label: ":wave: Show Cancel Signal"    
    command: |
      echo "BUILDKITE_CANCEL_SIGNAL is: $$BUILDKITE_CANCEL_SIGNAL"
  - label: ":wave: Show PLUGIN VALIDATION"
    command: |
      echo "BUILDKITE_PLUGIN_VALIDATION is: $BUILDKITE_PLUGIN_VALIDATION"
   - label: ":wave: Show PLUGIN VALIDATION"
    command: |
      echo "BUILDKITE_PLUGIN_VALIDATION is: $$BUILDKITE_PLUGIN_VALIDATION"    
