steps:
  - label: ":wave: Show Cancel Signal"
    command: |
      echo "BUILDKITE_CANCEL_SIGNAL is: $BUILDKITE_CANCEL_SIGNAL"
  - label: ":wave: Show Cancel Signal"    
    command: |
      echo "BUILDKITE_CANCEL_SIGNAL is: $$BUILDKITE_CANCEL_SIGNAL"
