steps:
  - label: "Do thing"
    command: echo "Build completed!"
notify:
  - slack:
      channels:
        - "buildkite#test-customers-issue"
      message: |
        Build #${BUILDKITE_BUILD_NUMBER}
