steps:
  - label: "Test Annotation with --job"
    command: |
      echo "Running annotation test..."
      echo "Job ID at runtime: $BUILDKITE_JOB_ID"
      buildkite-agent annotate "Annotation for Job: $BUILDKITE_JOB_ID" --style "info" --job "$BUILDKITE_JOB_ID"
