steps:
  - group: "Run Tests in Parallel"
    key: "test-group"
    steps:
      - label: ":test-tube: Run Tests Part 1"
        command:
          - "chmod +x ./tests/run_tests.sh"
          - "./tests/run_tests.sh"
        artifact_paths:
          - "test-results/*.xml"
      - label: ":test-tube: Run Tests Part 2"
        command:
          - "chmod +x ./tests/run_tests.sh"
          - "./tests/run_tests.sh"
        artifact_paths:
          - "test-results/*.xml"

  - wait

  - label: ":mag: Annotate Results"
    plugins:
      - junit-annotate#v1.0.0:
          artifacts: "test-results/*.xml"

agents:
     - queue=default-queue
  
