steps:
  - group: ":gandalf: Test Group"
    key: "test-group"
    steps:
      - command: ".buildkite/graceful_shutdown_script.sh"
        agent_query_rules:
         - queue=default-queue
        label: "Run tests script"


